version: "3.4"

services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT_LOCAL}"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - external

  source:
    container_name: source
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - external

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./data/nginx/templates:/etc/nginx/templates
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - external

  certbot:
    container_name: cert
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - external

networks:
  external:

volumes:
  db-data:
