version: "3.4"

services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    networks:
      - external
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  source:
    container_name: source
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - external

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "${PORT}:${PORT}"
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

networks:
  external:

volumes:
  db-data:
