version: "3.4"

services:
  db:
    container_name: post_db
    image: postgres
    restart: unless-stopped
    expose:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT_LOCAL}"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - external

  source:
    container_name: post_source
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${PROXY_IP}:${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - external

networks:
  external:

volumes:
  db-data:
